### ISSUE TITLE
Feature Request: Live Updates

### ISSUE THREAD

**Issue by tionis** [JordanKnott/taskcafe#13]
It would be awesome if edits to the boards (change in card data, card position etc.) would be instantly synced to all people watching the board.

In my use case this would be useful for shopping with someone else, but I could imagine it would also be useful for boards shown on TVs/second monitors etc to easily track progress.

**Comment by JordanKnott** [comment]
It's on the todo list to add polling (and real time updates through GraphQL subscriptions) however 
the real time updates portion might take a bit to implement. 

However I do plan on adding at least polling within probably a couple weeks so that changes made by others will at least eventually be seen without a manual refresh.

**Comment by JordanKnott** [comment]
Closed, see #89
