### ISSUE TITLE
Filling out "Add Team" on Main Page does not create a new team

### ISSUE THREAD

**Issue by kaleb112494** [JordanKnott/taskcafe#137]
Fresh pull of TaskCafe and successfully registered first account following #130 instructions. Created a Task successfully, but creating a Team failed. 

Application logs show:

`time="27-10-2021 22:34:24" level=info msg=middleware`
`time="27-10-2021 22:34:24" level=info msg="checking if logged in"`
`time="27-10-2021 22:34:24" level=info msg="fetching projects" reqID=obfuscated userID=obfuscated`
`time="27-10-2021 22:34:24" level=info msg="making projects" projectLength=0 reqID=obfuscated userID=obfuscated`

Environment is an UnRaid Docker container, pulled just a few moments ago. Can't seem to confirm a TaskCafe version.

**Comment by JordanKnott** [comment]
Pushed a [commit](https://github.com/JordanKnott/taskcafe/commit/3afd860534ea8ef9af159ba87b437920ad69d58c) that fixes this issue. Use the `taskcafe/taskcafe:latest` image if you would like to the use the fix.

**Comment by kaleb112494** [comment]
@JordanKnott Thank you! Not sure how the Docker container was built, but it doesn't seem to be set to pull :latest.

**Comment by assassin3232** [comment]
@JordanKnott still i am getting issue of teams not getting created
@kaleb112494 is your ones resolved.

**Comment by thomastthai** [comment]
@assassin3232, the latest docker image still has issues with team creation. @JordanKnott, you may want to reopen this ticket.

**Comment by kaleb112494** [comment]
@thomastthai this project appears to be dead - I would recommend Planka as a replacement.

**Comment by thomastthai** [comment]
@kaleb112494, it appears so. I'm learning Go and React so hopefully I can update it. It's a low priority among my other projects so it will take a while.

**Comment by NehorayK** [comment]
When modifying the actual HTML script that has been created using react, you can modify the HTML code a bit to create an href using onClick function.

Right (Mouse) click on the "Register" box in the /login page, press inspect, and insert after the color="primary" the following:

onClick="window.location.href='/register';"

should look the same as in the imgae.

![Image](https://github.com/user-attachments/assets/fa05f21c-e31e-4fb9-9131-1153a12d930a)

This will add a href that will redirect to the desired register page, but since im not that familiar with react, i cant change it on the source code itself ("index.tsx" file under the "/taskcafe-master/frontend/src/shared/components/Login" folder).
