### ISSUE TITLE
Feature Request: Mobile App

### ISSUE THREAD

**Issue by ilovepancakes95** [JordanKnott/taskcafe#62]
A mobile app would be BOMB but at the very least, a mobile friendly web interface could work as bare minimum.

Thanks for all your work on this project, looks very nice and has so much potential. Will be sending some beer/coffee/pizza money your way soon.

**Comment by JordanKnott** [comment]
A mobile app is planned though likely very far in the future. 

In near future, though: once I get the layout pretty much stable I plan on taking a pass to get at least the basic functionality working on mobile ( view and manage tasks, etc).

I'm going to close this issue since there is already an issue open for the mobile UI. (#11)
