### ISSUE TITLE
Feature: Collaborative editing

### ISSUE THREAD

**Issue by almereyda** [JordanKnott/taskcafe#89]
**Is your feature request related to a problem? Please describe.**

It is often that we are working synchronously together when looking at a kanban board. This means the displays can get out of sync, if one user edits something, and the other doesn't reload afterwards. This can lead to inconsistencies.

**Describe the solution you'd like**

An implementation of a real-time communication layer (through long polling, Websockets or WebRTC) together with a conflict resolution mechanism could build the foundation for collaborative editing of boards - not cards.

Pad like cards with real-time editing of their descriptions could then be some kind of Etherkanban, where changes are picked up immediately and distributed to other contributors. The Taskcafe Markdown editor is a nice approach at composing Markdown texts, almost like Ghost's and WordPress' card based editors nowadays.

**Describe alternatives you've considered**

An alternative could be to lock a board for writing through everyone, and only display changes made by the "presenter" to the "audience".

**Additional context**

Like in Trello/Wekan/Kanboard/Taiga ...

**Comment by JordanKnott** [comment]
Hey thanks for the feature request, however this is already planned and in the roadmap.

**Comment by JordanKnott** [comment]
I've enabled simple update polling so that at the very least if another user adds a task or something, you don't have to manually refresh the page to see the new changes!

I'd like to eventually move this over to a websockets system using GraphQL subscriptions, but I think this will be fine for the time being.

(the polling interval is 3 seconds, though that might change as I play with it more).
